version: '3.3'
services:
  app:
    build: .
    tty: true
    depends_on:
      - db
    ports:
      - "3333:3000"
    restart: always
    environment:
      MYSQL_HOST: db
      MYSQL_USER: username
      MYSQL_PASSWORD: passw@rd
      MYSQL_NAME: todo
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql.conf:/etc/mysql/conf.d/mysql.conf
    environment:
      MYSQL_ROOT_PASSWORD: passw@@@rd
      MYSQL_DATABASE: todo
      MYSQL_USER: username
      MYSQL_PASSWORD: passw@rd
volumes:
  db_data:
